FROM node:22-alpine
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN apk add --no-cache chromium

COPY package.json package-lock.json* ./
RUN npm ci

ENV NODE_ENV=production

COPY lib ./lib
COPY scripts ./scripts
COPY tsconfig.json ./tsconfig.json

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

USER nextjs

CMD ["npm", "run", "worker"]
